/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Network_CONSTANTS_H
#define Network_CONSTANTS_H

#include "Network_types.h"

namespace org { namespace ssdut { namespace sipesc { namespace network { namespace service {

class NetworkConstants {
 public:
  NetworkConstants();

};

extern const NetworkConstants g_Network_constants;

}}}}} // namespace

#endif
