/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Network_constants.h"

namespace org { namespace ssdut { namespace sipesc { namespace network { namespace service {

const NetworkConstants g_Network_constants;

NetworkConstants::NetworkConstants() {
}

}}}}} // namespace

