/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Types_CONSTANTS_H
#define Types_CONSTANTS_H

#include "Types_types.h"

namespace org { namespace ssdut { namespace sipesc { namespace network { namespace types {

class TypesConstants {
 public:
  TypesConstants();

  int64_t FILE_LEN_LIMIT;
};

extern const TypesConstants g_Types_constants;

}}}}} // namespace

#endif
