/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Types_constants.h"

namespace org { namespace ssdut { namespace sipesc { namespace network { namespace types {

const TypesConstants g_Types_constants;

TypesConstants::TypesConstants() {
  FILE_LEN_LIMIT = 16777216LL;

}

}}}}} // namespace

